global:
  scrape_interval: 1s

scrape_configs:
  - job_name: distributors
    static_configs:
      - targets:
          - 'host.docker.internal:8000'
          - 'host.docker.internal:8001'
    relabel_configs:
      - target_label: container
        replacement: distributor
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:8000'
        target_label: pod
        replacement: 'distributor-1'
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:8001'
        target_label: pod
        replacement: 'distributor-2'
        
  - job_name: ingesters
    static_configs:
      - targets:
          - 'host.docker.internal:8002'
          - 'host.docker.internal:8003'
          - 'host.docker.internal:8004'
    relabel_configs:
      - target_label: container
        replacement: ingester
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:8002'
        target_label: pod
        replacement: 'ingester-1'
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:8003'
        target_label: pod
        replacement: 'ingester-2'
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:8004'
        target_label: pod
        replacement: 'ingester-3'

    always_scrape_classic_histograms: true