{
 "title": "Reactive concurrency limiter",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Distributors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distributor RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(cortex_distributor_received_requests_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(cortex_request_duration_seconds{container=\"distributor\",route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[1m])))*1e3",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(cortex_request_duration_seconds{container=\"distributor\",route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[1m])))*1e3",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(irate(cortex_request_duration_seconds_sum{container=\"distributor\",route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[1m]))*1e3\n/\nsum(irate(cortex_request_duration_seconds_count{container=\"distributor\",route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[1m]))*1e3",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distributor Per Pod p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (pod)(irate(cortex_request_duration_seconds{container=\"distributor\",route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push|otlp_v1_metrics|api_v1_push_influx_write\"}[1m])))*1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(process_cpu_seconds_total{container=~\"distributor\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{container=\"distributor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributor Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod) (cortex_inflight_requests{container=\"distributor\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod)(cortex_ingester_adaptive_limiter_inflight_requests{request_type=\"push\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingester Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod) (cortex_inflight_requests{container=\"ingester\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod)(cortex_ingester_adaptive_limiter_inflight_requests{request_type=\"push\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rejected distributor requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(cortex_distributor_instance_rejected_requests_total{container=\"distributor\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected ingester requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(cortex_ingester_instance_rejected_requests_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Pushes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod)(cortex_ingester_adaptive_limiter_blocked_requests{request_type=\"push\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prioritizer Rejection Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cortex_ingester_rejection_rate{}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}